python/pystagram/users/posts/urls.py
from django.urls import path
from . import views

app_name='posts'
urlpatterns=[
    path("feeds/", views.feeds,name="feeds"),
    path("comment_add/", views.comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", views.comment_delete, name="comment_delete"),
    path("post_add/", views.post_add, name="post_add"),
    path("tags/<str:tag_name>/",views.tags, name="tags"),
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/like/", views.post_like, name="like"),
]

python/pystagram/users/pystagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index ),
    path('users/', include("users.urls")),
    path("posts/", include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)
else : 
    from django.views.static import serve
    from django.urls import re_path

    urlpatterns+= re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    urlpatterns+= re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

python/pystagram/users/urls.py
from django.urls import path
from . import views

app_name= "users"
urlpatterns= [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("<int:user_id>/profile/", views.profile, name="profile"),
    path("<int:user_id>/following", views.following, name="following"),
    path("<int:user_id>/followers", views.followers, name="followers"),
    path("<int:user_id>/follow/", views.follow , name="follow"),
]

python/pystagram/users/posts/models.py
from django.db import models


# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content=models.TextField("내용")
    created=models.DateTimeField("생성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name='해시태그 목록', blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"
class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진", upload_to="post")

class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    create = models.DateTimeField("생성일시", auto_now_add=True)

class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

python/pystagram/users/templates/users/followers.html
{% extends 'base_profile.html' %}

{% block bottom_data %}
<div class="relationships">
    <h3>Followers</h3>
    {% for relationship in relationships %}
    <div class="relationship">
        <a href="{% url 'users:profile' user_id=relationship.from_user.id %}">
            {% if relationship.from_user.profile_image and relationship.from_user.profile_image.photo %}
            <img src="{{relationship.from_user.profile_image.url}}">
            {% endif %}
            <div class="relationship-info">
                <span>{{ relationship.from_user.username}}</span>
                <span>{{ relationship.created|date:'y.m.d'}}</span>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

python/pystagram/users/templates/users/following.html
{% extends 'base_profile.html' %}

{% block bottom_data %}
<div class="relationships">
    <h3>Following</h3>
    {% for relationship in relationships %}
    <div class="relationship">
        <a href="{% url 'users:profile' user_id=relationship.to_user.id %}">
            {% if relationship.from_user.profile_image and relationship.from_user.profile_image.photo %}
            <img src="{{relationship.to_user.profile_image.url}}">
            {% endif %}
            <div class="relationship-info">
                <span>{{ relationship.to_user.username}}</span>
                <span>{{ relationship.created|date:'y.m.d'}}</span>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

python/pystagram/users/templates/users/login.html
{% extends 'base.html' %}
{% block contents %}
<div id="login">
    <form method="POST">
        <h1>Pystagram</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'users:signup' %}">
            <p class="signup">회원가입</p>
        </a>
        <button type="submit" class="btn btn-login">로그인</button>
    </form>
</div>
{% endblock %}

python/pystagram/users/templates/users/profile.html
{% extends 'base_profile.html' %}

{% block bottom_data %}
<!-- 사용자가 작성한 Post 목록-->
<div class="post-grid-container">
    {% for post in user.post_set.all %}
    {% if post.postimage_set.first and post.postimage_set.first.photo %}
    <a href="{% url 'posts:post_detail' post_id=post.id %}">
        <div class="post-grid">
            <img src="{{post.postimage_set.first.photo.url}}" alt="">
        </div>
    </a>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

python/pystagram/users/templates/users/signup.html
{% extends 'base.html' %}
{% block contents %}
<div id="signup">
    <form method="POST" enctype="multipart/form-data">
        <h1>SIGNUP</h1>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-signup">회원가입</button>
        <a href="{% url 'users:login' %}">로그인</a>
    </form>
</div>
{% endblock %}