python/pystagram/users/posts/urls.py
from django.urls import path
from . import views

app_name='posts'
urlpatterns=[
    path("feeds/", views.feeds,name="feeds"),
    path("comment_add/", views.comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", views.comment_delete, name="comment_delete"),
    path("post_add/", views.post_add, name="post_add"),
    path("tags/<str:tag_name>/",views.tags, name="tags"),
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/like/", views.post_like, name="like"),
]

python/pystagram/users/pystagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index ),
    path('users/', include("users.urls")),
    path("posts/", include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)
else : 
    from django.views.static import serve
    from django.urls import re_path

    urlpatterns+= re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    urlpatterns+= re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

python/pystagram/users/urls.py
from django.urls import path
from . import views

app_name= "users"
urlpatterns= [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("<int:user_id>/profile/", views.profile, name="profile"),
    path("<int:user_id>/following", views.following, name="following"),
    path("<int:user_id>/followers", views.followers, name="followers"),
    path("<int:user_id>/follow/", views.follow , name="follow"),
]

python/pystagram/users/posts/models.py
from django.db import models


# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content=models.TextField("내용")
    created=models.DateTimeField("생성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name='해시태그 목록', blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"
class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진", upload_to="post")

class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    create = models.DateTimeField("생성일시", auto_now_add=True)

class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

python/pystagram/users/posts/forms.py
from django import forms
from posts.models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets ={
            "content" : forms.Textarea(
                attrs={
                    "placeholder": "댓글달기...",
                }
            )
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "content",
        ]

python/pystagram/users/posts/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect, HttpResponseForbidden
from posts.models import Post, Comment, PostImage, HashTag
from . import forms
from django.views.decorators.http import require_POST
from django.urls import reverse


# Create your views here.
def feeds(request):
    user = request.user

    # is_authenticated = user.is_authenticated

    # print("user:", user)
    # print("is_authenticated:", is_authenticated)

    if not request.user.is_authenticated:
        return redirect("users:login")
    
    posts = Post.objects.all()
    comment_form = forms.CommentForm()
    context = {
        "posts": posts,
        "comment_form": comment_form,}
    return render(request,"posts/feeds.html", context)

@require_POST # 댓글 작성을 처리할 View, Post 요청만 허용
def comment_add(request):

    form = forms.CommentForm(data=request.POST)
    if form.is_valid():
        # commit=False 옵션으로 메모상에 Comment 객체 생성
        comment = form.save(commit=False)

        # Comment 생성에 필요한 사용자 정보를 request에서 가져와 할당
        comment.user = request.user

        comment.save()

        # print(comment.id)
        # print(comment.content)
        # print(comment.user)
        # print(comment.post)
        # if request.GET.get("next"):
        #     url_next = request.GET.get("next")
        # else :
        #     url_next = reverse("posts:feeds") + f"#post-{comment.post.id}"
        
        url_next = request.GET.get('next')
        return HttpResponseRedirect(url_next)

@require_POST
def comment_delete(request, comment_id):
    if request.method == "POST":
        comment = Comment.objects.get(id=comment_id)
        if comment.user == request.user:
            comment.delete()
            url = reverse("posts:feeds") + f"#post-{comment.post.id}"
            return HttpResponseRedirect(url)
        else:
            return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다.")

def post_add(request):
    if request.method == "POST":
        # request.POST로 온 데이터 ("content")는 PostForm으로 처리
        form = forms.PostForm(request.POST)

        if form.is_valid():
            # Post의 "user" 값은 request에서 가져와 자동 할당한다.
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            #Post를 생성한 후
            # request.FILES.getlist("images")로 전송된 이미지들을 순회하며 PostImage 객체를 생성한다.
            for image_file in request.FILES.getlist("images"):
                # request.FILES 또는 request.FILES.getlist()로 가져온 파일은
                # Model의 ImageField 부분에 곧바로 할당한다.
                PostImage.objects.create(
                    post=post,
                    photo=image_file,
                )

            # "tags"에 전달된 문자열을 분리해 HashTag 생성
            tag_string = request.POST.get("tags")
            if tag_string:
                tag_names = {tag_name.strip() for tag_name in tag_string.split(',')}
                for tag_name in tag_names:
                    tag, _ = HashTag.objects.get_or_create(name=tag_name)
                    post.tags.add(tag)
            url = f"{reverse('posts:feeds')}#post-{post.id}"
            return HttpResponseRedirect(url)
    else:
        form = forms.PostForm()
    context = { "form" : form }
    return render(request, "posts/post_add.html", context)

def tags(request, tag_name):
    try:
        tag = HashTag.objects.get(name=tag_name)
    except HashTag.DoesNotExist:
        # tag_name에 해당하는 HashTag를 찾지 못한 경우, 빈 QuerySet을 돌려준다.
        posts= Post.objects.none()
    else :
        #tags (M2M 필드)에 찾은 HashTag 객체가 있는 필터
        posts = Post.objects.filter(tags=tag)

    context = {
    "tag_name" : tag_name,
    "posts" : posts,
    }
    return render(request, 'posts/tags.html', context)

def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = forms.CommentForm()
    context = {
        "post": post,
        "comment_form" : comment_form,
        }
    return render(request, "posts/post_detail.html", context)

def post_like(request, post_id):
    post = Post.objects.get(id=post_id)
    user = request.user

    # 사용자가 "좋아요를 누른 Post 목록"에 "좋아요 버튼을 누른  Post"가 존재한다면
    if user.like_posts.filter(id=post.id).exists():
        # 좋아요 목록에서 삭제한다
        user.like_posts.remove(post)
    # 존재하지 않는다면 좋아요 목록에 추가
    else:
        user.like_posts.add(post)
    
    # next로 값이 전달되었다면 해당 위치로, 전달되지 않았다면 피드 페이지에서 해당 Post 위치로 이동
    url_next = request.GET.get("next") or reverse("posts:feeds") + f"#post-{post.id}"
    return HttpResponseRedirect(url_next)

python/pystagram/users/posts/templates/posts/feeds.html
{% extends 'base_slider.html' %}

{% load custom_tags %}

{% block contents %}
{% include 'nav.html' %}

<div id="feeds" class="post-container">
    {% for post in posts %}
    {% url 'posts:feeds' as action_redirect_to %}
    {% include 'posts/post.html' with action_redirect_url=action_redirect_to|concat:'#post-'|concat:post.id %}
    {% endfor %}
</div>

{% endblock %}

python/pystagram/users/posts/templates/posts/post.html
<article id="post-{{post.id}}" class="post">
    <header class="post-header">
        <div>
            <a href="{% url 'users:profile' user_id=post.user.id %}">
                {% if post.user.profile_image %}
                <img src="{{post.user.profile_image.url}}">
                {% endif %}
                <span>{{ post.user.username }}</span>
            </a>
        </div>
        <!-- 글의 작성자가 로그인한 사용자라면 팔로우 버튼을 표시하지 않는다.-->
        <!-- (자기 자신을 팔로우하는 일은 없어야하니까)-->
        {% if user != post.user %}
        <div>
            {% include 'follow.html' %}
        </div>
        {% endif %}
    </header>
    <div class="post-images splide">
        <div class="splide__track">
            <ul class="splide__list">
                {% for image in post.postimage_set.all %}
                {% if image.photo %}
                <li class="splide__slide">
                    <div class="post-img">
                        <img src="{{ image.photo.url }}">
                    </div>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="post-content">
        {{post.content|linebreaksbr}}
        <div class="post-tags">
            {% for tag in post.tags.all %}
            <a href="{% url 'posts:tags' tag_name=tag.name %}">#{{tag.name}}</a>
            {% endfor %}
        </div>
    </div>
    <div class="post-buttons">
        <form action="{% url 'posts:like' post_id=post.id %}?next={{ action_redirect_url }}" method="POST">
            {% csrf_token %}
            <button type="submit" {% if user in post.like_users.all %} style="color: red;" {% endif %}>
                Likes({{post.like_users.count}})
            </button>
        </form>
        <span>Comments({{post.comment_set.count}})</span>
    </div>
    <div class="post-comments">
        <ul>
            {% for comment in post.comment_set.all %}
            <li>
                <span>{{ comment.user.username }}</span>
                <span>{{ comment.content }}</span>

                <!-- 댓글 삭제 Form 추가-->
                {% if user == comment.user %}
                <form method="POST" action="{% url 'posts:comment_delete' comment_id=comment.id %}">
                    {% csrf_token %}
                    <button type="submit">삭제</button>
                </form>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>
    <small>{{ post.created }}</small>
    <div class="post-comment-create">
        <form method="POST" action="{% url 'posts:comment_add' %}?next={{action_redirect_url}}">
            {% csrf_token %}
            <!-- 사용자가 직접 입력하지 않는 고정된 데이터를 form 내부에 위치-->
            <input type="hidden" name="post" value="{{post.id}}">
            {{comment_form.content}}
            <button type="submit">게시</button>
        </form>
    </div>
</article>

python/pystagram/users/posts/templates/posts/post_add.html
{% extends 'base.html' %}
{% block contents %}

<nav>
    <h1>
        <a href="/posts/feeds/">Pystagram</a>
    </h1>
    <a href="/users/logout/">Logout</a>
</nav>
<div id="post-add">
    <h1>Post 작성</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label for="id_images">이미지</label>
            <input id="id_images" name="images" type="file" multiple>
        </div>
        {{ form.as_p }}
        <div>
            <label for="id_tags">해시태그</label>
            <input id="id_tags" name="tags" type="text" placeholder="쉼표(,)로 구분하여 여러 태그 입력">
        </div>
        <button type="submit">게시</button>
    </form>
</div>
{% endblock %}

python/pystagram/users/posts/templates/posts/post_detail.html
{% extends 'base_slider.html' %}
{% block contents %}
{% include 'nav.html' %}
<div id="feeds" class="post-container">
    {% url 'posts:post_detail' post.id as action_redirect_to %}
    {% include 'posts/post.html' with action_redirect_url=action_redirect_to %}
</div>

<script>
    const elms = document.getElementsByClassName('splide')
    for (let i = 0; i < elms.length; i++) {
        new Splide(elms[i]).mount();
    }
</script>

{% endblock %}

python/pystagram/users/posts/templates/posts/tags.html
{% extends 'base_slider.html' %}
{% block contents %}
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">Pystagram</a>
    </h1>
    <a href="{% url 'posts:post_add'}">Add Post</a>
    <a href="{% url 'users:logout' %}">Logout</a>
</nav>
<div id="tags">
    <header class="tags-header">
        <h2>#{{ tag_name }}</h2>
        <div>게시물 {{ posts.count }}</div>
    </header>
    <div class="post-grid-container">
        {% for post in posts %}
        {% if post.postimage_set.first and post.postimage_set.first.photo %}
        <div class="post-grid">
            <a href="{% url 'posts:post_detail' post_id=post.id %}">
                <img src="{{post.postimage_set.first.photo.url}}" alt="사진이 없습니다">
            </a>
        </div>
        {% else %}
        <div class="post-grid">
            <a href="{% url 'posts:post_detail' post_id=post.id %}">
                <p> 사진이 비어 있네요 .. </p>
            </a>
        </div>
        {% endif %}

        {% empty %}
        <p> 검색된 게시물이 없습니다. </p>
        {% endfor %}
    </div>
</div>

{% endblock %}