python/pystagram/users/config/urls.py
from django.urls import path
from . import views

app_name = "config"
urlpatterns=[
    path("", views.index , name="config_index")
]

python/pystagram/users/posts/urls.py
from django.urls import path
from . import views

app_name='posts'
urlpatterns=[
    path("feeds/", views.feeds,name="feeds"),
    path("comment_add/", views.comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", views.comment_delete, name="comment_delete"),
    path("post_add/", views.post_add, name="post_add"),
    path("tags/<str:tag_name>/",views.tags, name="tags"),
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/like/", views.post_like, name="like"),
]

python/pystagram/users/pystagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index ),
    path('users/', include("users.urls")),
    path("posts/", include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)
else : 
    from django.views.static import serve
    from django.urls import re_path

    urlpatterns+= re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    urlpatterns+= re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

python/pystagram/users/urls.py
from django.urls import path
from . import views

app_name= "users"
urlpatterns= [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("<int:user_id>/profile/", views.profile, name="profile"),
    path("<int:user_id>/following", views.following, name="following"),
    path("<int:user_id>/followers", views.followers, name="followers"),
    path("<int:user_id>/follow/", views.follow , name="follow"),
]

python/pystagram/users/config/models.py
from django.db import models

# Create your models here.

python/pystagram/users/posts/models.py
from django.db import models


# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content=models.TextField("내용")
    created=models.DateTimeField("생성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name='해시태그 목록', blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"
class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진", upload_to="post")

class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    create = models.DateTimeField("생성일시", auto_now_add=True)

class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

python/pystagram/users/config/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        return redirect("posts:feeds")
    else :
        return redirect("users:login")
    # context = {
    #     "of_course" : "of_course"
    # }
    # return render(request, 'config/index.html', context)

python/pystagram/users/config/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Pystagram</title>
    {% block head %} {% endblock %}
</head>

<body>
    {% block base_content %}{% endblock %}
</body>

</html>

python/pystagram/users/config/templates/base.html
{% extends '_base.html' %}

{% block base_content %}
{% block contents %} {% endblock %}
{% endblock %}

python/pystagram/users/config/templates/base_nav.html
{% extends '_base.html' %}

{% block base_content %}
{% include 'nav.html' %}
{% block contents %}{% endblock %}
{% endblock %}

python/pystagram/users/config/templates/base_profile.html
{% extends 'base_nav.html' %}

{% block contents %}
<div id="profile">
    <div class="profile-container">
        <div class="info">
            <!-- 프로필 이미지 영역 -->
            {% if user.profile_image %}
            <div class="profile_img">
                <img src="{{user.profile_image.url}}">
            </div>
            {% endif %}

            <!-- 사용자 정보 영역 -->
            <div class="info-texts">
                <div class="profile-name-follow">
                    <h1>{{user.username}}</h1>
                    {% if not is_my_profile %}
                    {% include 'follow_profile.html' %}
                    {% endif %}
                </div>


                <div class="counts">
                    <dl>
                        <dt class="profile-dl-item">Posts</dt>
                        <dd class="profile-dl-item">
                            <a href="{% url 'users:profile' user_id=user.id %}">
                                {{user.post_set.count}}
                            </a>
                        </dd>
                        <dt class="profile-dl-item">Followers</dt>
                        <dd class="profile-dl-item">
                            <a href="{% url 'users:followers' user_id=user.id %}">
                                {{user.followers.count}}
                            </a>
                        </dd>
                        <dt class="profile-dl-item">Following</dt>
                        <dd class="profile-dl-item">
                            <a href="{% url 'users:following' user_id=user.id %}">
                                {{user.following.count}}
                            </a>
                        </dd>
                    </dl>
                </div>
                <p>{{ user.short_description }}</p>
            </div>
        </div>
        {% block bottom_data %} {% endblock %}
    </div>
</div>
{% endblock %}

python/pystagram/users/config/templates/base_slider.html
{% extends '_base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'splide.css' %}">
<script src="{% static 'splide.js' %}"></script>
{% endblock %}

{% block base_content %}
{% include 'nav.html' %}
{% block contents %}{% endblock %}
<script>
    const elms = document.getElementsByClassName('splide')
    for (let i = 0; i < elms.length; i++) {
        new Splide(elms[i]).mount();
    }
</script>
{% endblock %}

python/pystagram/users/config/templates/follow.html
<form action="{% url 'users:follow' user_id=post.user.id %}?next={{action_redirect_url}}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-follow">
        <!-- 이 Post 작성자가 이미 자신의 팔로잉 목록에 포함된 경우-->
        {% if post.user in user.following.all %}
        Unfollow
        <!-- 이 Post의 작성자를 아직  팔로잉 하지 않은 경우 -->
        {% else %}
        follow
        {% endif %}
    </button>
</form>

python/pystagram/users/config/templates/follow_profile.html
<form action="{% url 'users:follow' user_id=user.id %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-follow">
        <!-- 이 Post 작성자가 이미 자신의 팔로잉 목록에 포함된 경우-->
        {% if user in current_user.following.all %}
        Unfollow
        <!-- 이 Post의 작성자를 아직  팔로잉 하지 않은 경우 -->
        {% else %}
        follow
        {% endif %}
    </button>
</form>

python/pystagram/users/config/templates/nav.html
<nav>
    <h1><a href="{% url 'posts:feeds' %}">Pystagram</a></h1>
    <a href="{% url 'users:profile' user_id=user.id %}">{{user.username}} 님</a>
    <a href="{% url 'posts:post_add' %}">Add post</a>
    <a href="{% url 'users:logout' %}">Logout</a>
</nav>